{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a6ff1b95-01c8-4eb5-8a7d-bf1b155db34c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import requests\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "from tensorflow.keras.models import load_model\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "\n",
    "# =====================================\n",
    "# PAGE CONFIG\n",
    "# =====================================\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"AI Spam Detection Hub\",\n",
    "    page_icon=\"📩\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# =====================================\n",
    "# CUSTOM CSS\n",
    "# =====================================\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "\n",
    ".stApp {\n",
    "    background: linear-gradient(\n",
    "        135deg,\n",
    "        #0f172a,\n",
    "        #1e293b\n",
    "    );\n",
    "}\n",
    "\n",
    ".big-title{\n",
    "    text-align:center;\n",
    "    font-size:55px;\n",
    "    font-weight:bold;\n",
    "    color:white;\n",
    "}\n",
    "\n",
    ".subtitle{\n",
    "    text-align:center;\n",
    "    font-size:20px;\n",
    "    color:#cbd5e1;\n",
    "}\n",
    "\n",
    ".result-card{\n",
    "    padding:20px;\n",
    "    border-radius:20px;\n",
    "    background:rgba(255,255,255,0.08);\n",
    "    backdrop-filter:blur(10px);\n",
    "    border:1px solid rgba(255,255,255,0.15);\n",
    "}\n",
    "\n",
    ".footer{\n",
    "    text-align:center;\n",
    "    color:#94a3b8;\n",
    "    margin-top:30px;\n",
    "}\n",
    "\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# =====================================\n",
    "# LOAD MODELS\n",
    "# =====================================\n",
    "\n",
    "@st.cache_resource\n",
    "def load_resources():\n",
    "\n",
    "    lstm_model = load_model(\n",
    "        \"lstm_model.keras\"\n",
    "    )\n",
    "\n",
    "    bilstm_model = load_model(\n",
    "        \"bilstm_model.keras\"\n",
    "    )\n",
    "\n",
    "    with open(\n",
    "        \"tokenizer.pkl\",\n",
    "        \"rb\"\n",
    "    ) as f:\n",
    "\n",
    "        tokenizer = pickle.load(f)\n",
    "\n",
    "    return (\n",
    "        lstm_model,\n",
    "        bilstm_model,\n",
    "        tokenizer\n",
    "    )\n",
    "\n",
    "lstm_model, bilstm_model, tokenizer = load_resources()\n",
    "\n",
    "MAX_LEN = 50\n",
    "\n",
    "# =====================================\n",
    "# PREDICTION FUNCTION\n",
    "# =====================================\n",
    "\n",
    "def predict(model, text):\n",
    "\n",
    "    seq = tokenizer.texts_to_sequences(\n",
    "        [text]\n",
    "    )\n",
    "\n",
    "    padded = pad_sequences(\n",
    "        seq,\n",
    "        maxlen=MAX_LEN,\n",
    "        padding=\"post\",\n",
    "        truncating=\"post\"\n",
    "    )\n",
    "\n",
    "    prob = model.predict(\n",
    "        padded,\n",
    "        verbose=0\n",
    "    )[0][0]\n",
    "\n",
    "    label = (\n",
    "        \"🚨 SPAM\"\n",
    "        if prob > 0.5\n",
    "        else \"✅ HAM\"\n",
    "    )\n",
    "\n",
    "    confidence = (\n",
    "        prob\n",
    "        if prob > 0.5\n",
    "        else 1 - prob\n",
    "    )\n",
    "\n",
    "    return label, confidence\n",
    "\n",
    "# =====================================\n",
    "# HEADER\n",
    "# =====================================\n",
    "\n",
    "st.markdown(\n",
    "    '<p class=\"big-title\">📩 AI Spam Detection Hub</p>',\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "st.markdown(\n",
    "    '<p class=\"subtitle\">Comparing LSTM vs Bidirectional LSTM</p>',\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "st.write(\"\")\n",
    "\n",
    "# =====================================\n",
    "# SIDEBAR\n",
    "# =====================================\n",
    "\n",
    "st.sidebar.title(\"📌 Project Info\")\n",
    "\n",
    "st.sidebar.success(\"\"\"\n",
    "SMS Spam Detection\n",
    "\n",
    "Models Used:\n",
    "\n",
    "✔ LSTM\n",
    "\n",
    "✔ Bidirectional LSTM\n",
    "\n",
    "Dataset:\n",
    "\n",
    "SMS Spam Collection Dataset\n",
    "\"\"\")\n",
    "\n",
    "st.sidebar.markdown(\"---\")\n",
    "\n",
    "st.sidebar.write(\n",
    "    \"Enter an SMS message and compare both models.\"\n",
    ")\n",
    "\n",
    "# =====================================\n",
    "# INPUT\n",
    "# =====================================\n",
    "\n",
    "message = st.text_area(\n",
    "    \"✍️ Enter SMS Message\",\n",
    "    height=180,\n",
    "    placeholder=\"Example: Congratulations! You won a free iPhone...\"\n",
    ")\n",
    "\n",
    "model_choice = st.radio(\n",
    "    \"Choose Prediction Mode\",\n",
    "    [\n",
    "        \"LSTM\",\n",
    "        \"BiLSTM\",\n",
    "        \"Compare Both\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# =====================================\n",
    "# BUTTON\n",
    "# =====================================\n",
    "\n",
    "if st.button(\"🚀 Detect Message\"):\n",
    "\n",
    "    if message.strip() == \"\":\n",
    "\n",
    "        st.warning(\n",
    "            \"Please enter a message.\"\n",
    "        )\n",
    "\n",
    "    else:\n",
    "\n",
    "        # -----------------------\n",
    "        # LSTM ONLY\n",
    "        # -----------------------\n",
    "\n",
    "        if model_choice == \"LSTM\":\n",
    "\n",
    "            label, confidence = predict(\n",
    "                lstm_model,\n",
    "                message\n",
    "            )\n",
    "\n",
    "            st.success(\n",
    "                f\"Prediction: {label}\"\n",
    "            )\n",
    "\n",
    "            st.progress(\n",
    "                float(confidence)\n",
    "            )\n",
    "\n",
    "            st.write(\n",
    "                f\"Confidence: {confidence:.2%}\"\n",
    "            )\n",
    "\n",
    "        # -----------------------\n",
    "        # BILSTM ONLY\n",
    "        # -----------------------\n",
    "\n",
    "        elif model_choice == \"BiLSTM\":\n",
    "\n",
    "            label, confidence = predict(\n",
    "                bilstm_model,\n",
    "                message\n",
    "            )\n",
    "\n",
    "            st.success(\n",
    "                f\"Prediction: {label}\"\n",
    "            )\n",
    "\n",
    "            st.progress(\n",
    "                float(confidence)\n",
    "            )\n",
    "\n",
    "            st.write(\n",
    "                f\"Confidence: {confidence:.2%}\"\n",
    "            )\n",
    "\n",
    "        # -----------------------\n",
    "        # COMPARE BOTH\n",
    "        # -----------------------\n",
    "\n",
    "        else:\n",
    "\n",
    "            lstm_label, lstm_conf = predict(\n",
    "                lstm_model,\n",
    "                message\n",
    "            )\n",
    "\n",
    "            bilstm_label, bilstm_conf = predict(\n",
    "                bilstm_model,\n",
    "                message\n",
    "            )\n",
    "\n",
    "            col1, col2 = st.columns(2)\n",
    "\n",
    "            with col1:\n",
    "\n",
    "                st.markdown(\n",
    "                    \"## 🔹 LSTM\"\n",
    "                )\n",
    "\n",
    "                st.metric(\n",
    "                    \"Prediction\",\n",
    "                    lstm_label\n",
    "                )\n",
    "\n",
    "                st.progress(\n",
    "                    float(lstm_conf)\n",
    "                )\n",
    "\n",
    "                st.write(\n",
    "                    f\"Confidence: {lstm_conf:.2%}\"\n",
    "                )\n",
    "\n",
    "            with col2:\n",
    "\n",
    "                st.markdown(\n",
    "                    \"## 🔹 BiLSTM\"\n",
    "                )\n",
    "\n",
    "                st.metric(\n",
    "                    \"Prediction\",\n",
    "                    bilstm_label\n",
    "                )\n",
    "\n",
    "                st.progress(\n",
    "                    float(bilstm_conf)\n",
    "                )\n",
    "\n",
    "                st.write(\n",
    "                    f\"Confidence: {bilstm_conf:.2%}\"\n",
    "                )\n",
    "\n",
    "            winner = (\n",
    "                \"BiLSTM\"\n",
    "                if bilstm_conf > lstm_conf\n",
    "                else \"LSTM\"\n",
    "            )\n",
    "\n",
    "            st.success(\n",
    "                f\"🏆 Higher Confidence Model: {winner}\"\n",
    "            )\n",
    "\n",
    "            # -----------------------\n",
    "            # GAUGE CHART\n",
    "            # -----------------------\n",
    "\n",
    "            spam_score = max(\n",
    "                lstm_conf,\n",
    "                bilstm_conf\n",
    "            ) * 100\n",
    "\n",
    "            fig = go.Figure(\n",
    "                go.Indicator(\n",
    "                    mode=\"gauge+number\",\n",
    "                    value=spam_score,\n",
    "                    title={\n",
    "                        'text': \"Confidence Score\"\n",
    "                    },\n",
    "                    gauge={\n",
    "                        'axis': {\n",
    "                            'range': [0,100]\n",
    "                        }\n",
    "                    }\n",
    "                )\n",
    "            )\n",
    "\n",
    "            st.plotly_chart(\n",
    "                fig,\n",
    "                use_container_width=True\n",
    "            )\n",
    "\n",
    "# =====================================\n",
    "# FOOTER\n",
    "# =====================================\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <div class='footer'>\n",
    "    Built with Streamlit • LSTM vs BiLSTM Spam Detection\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
